server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9094

    properties:
      "[schema.registry.url]": http://localhost:8081

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
      group-id: api-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      properties:
        "[specific.avro.reader]": true
