execution:
  docker:
    image: codestream-python-runner:latest
    timeout-seconds: 3
    max-output-bytes: 10000
    memory-mb: 128
    cpus: 0.5
    pids-limit: 64

spring:
  kafka:
    bootstrap-servers: localhost:9094

    properties:
      "[schema.registry.url]": http://localhost:8081

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
      group-id: worker-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      properties:
        "[specific.avro.reader]": true