<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.pipeline</groupId>
    <artifactId>code-stream</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>worker-service</artifactId>

  <dependencies>

    <!-- Spring Boot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>

    <!-- Shared models + SQS helper -->
    <dependency>
      <groupId>com.pipeline</groupId>
      <artifactId>common</artifactId>
      <version>1.0.0</version>
    </dependency>

    <!-- AWS SQS -->
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>sqs</artifactId>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <mainClass>com.pipeline.worker.WorkerApplication</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
